//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revamp_LatestSightings {
    
    
    public partial class _default {
        
        /// <summary>
        /// hbmsection control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Revamp_LatestSightings.uc_HomePage_Main_Container_Section hbmsection;
    }
}
